--Complex joins

SELECT * FROM PETS AS A
INNER JOIN ProceduresHistory AS B
ON A.PETID = B.PETID
LEFT JOIN ProceduresDetails AS C
ON B.PROCEDURETYPE = C.PROCEDURETYPE 
AND B.PROCEDURESUBCODE = C.PROCEDURESUBCODE