--Tips and Tricks

SELECT PETS.NAME, OWNERS.NAME
FROM PETS
LEFT JOIN OWNERS
ON PETS.OWNERID = OWNERS.OWNERID
WHERE LEFT(PETS.NAME, 1) = LEFT(OWNERS.NAME, 1)

SELECT PETS.NAME, OWNERS.NAME
FROM PETS
LEFT JOIN OWNERS
ON PETS.OWNERID = OWNERS.OWNERID
WHERE PETS.NAME = 'COOKIE'

--ALIASES FOR TABLES
SELECT A.NAME, B.NAME
FROM PETS AS A 
LEFT JOIN OWNERS AS B
ON A.OWNERID = B.OWNERID
WHERE LEFT(A.NAME, 1) = LEFT(B.NAME, 1)

--ALIASES FOR COLUMNS
SELECT A.NAME AS PETNAME, B.NAME AS OWNERNAME
FROM PETS AS A 
LEFT JOIN OWNERS AS B
ON A.OWNERID = B.OWNERID
WHERE LEFT(A.NAME, 1) = LEFT(B.NAME, 1)

--RIGHT JOINS
SELECT A.NAME AS PETNAME, B.NAME AS OWNERNAME
FROM OWNERS AS B
RIGHT JOIN PETS AS A
ON A.OWNERID = B.OWNERID

