--NORMALIZATION 2NF

SELECT * FROM TRANSACTIONS;

/*CANDIDATE KEYS/PRIME ATTRIBUTES
-TRANSACTIONID
-TIMESTAMPSEC  W/ CUSTOMERID

NON-PRIME ATTRIBUTES
-FIRSTNAME
-SURNAME
-SHIPPING_DATE
-LOYALTY_DISCOUNT
*/


--SEPERATE CUSTOMER SPECIFIC COLUMNS
SELECT customerID,
firstname,
surname,
shipping_state,
loyalty_discount
INTO TMP
FROM Transactions
--3455 rows

SELECT * FROM TMP

--REMOVE DUPLICATES
SELECT DISTINCT * 
INTO CUSTOMERS
FROM TMP
--942 ROWS

SELECT * FROM CUSTOMERS
--2NF CONFIRMED

--BACK TO TRANSACTIONS TABLE
SELECT * FROM TRANSACTIONS
--REMOVE CUSTOMER-SPECIFIC COLUMNS
--LEAVE THE 'CUSTOMERID' COLUMN

ALTER TABLE TRANSACTIONS
DROP COLUMN firstname,
			surname,
			shipping_state,
			loyalty_discount

SELECT * FROM TRANSACTIONS
--2NF CONFIRMED

DROP TABLE TMP