--NORMALIZATION 3NF

SELECT * FROM CUSTOMERS
--3NF CONFIRMED

SELECT * FROM TRANSACTIONS;
--3NF NOT CONFIRMED

--SEPERATE ITEM SPECIFIC COLUMNS
SELECT item,
		[description],
		retail_price
INTO TMP
FROM TRANSACTIONS;

SELECT * FROM TMP
--3455 ROWS

--REMOVE DUPLICATES
SELECT DISTINCT * 
INTO Items
FROM TMP
--126 ROWS

--CHECK
SELECT * FROM ITEMS
--3NF CONFIRMED

--REMOVE THE EXTRACTED ROWS FROM THE TRANSACTIONS TABLE
--BUT KEEP THE FOREIGN KEY 'ITEM'
SELECT * FROM TRANSACTIONS

ALTER TABLE TRANSACTIONS
DROP COLUMN [description],
			retail_price

SELECT * FROM TRANSACTIONS
--3NF CONFIRMED

DROP TABLE TMP


